### PR TITLE
Fix air quality measurement duration

### PR DESCRIPTION
**Pull request by dhasenfratz**
The duration for an air quality measurement is 50ms.

Please see the data sheet (https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/9_Gas_Sensors/Sensirion_Gas_Sensors_SGP30_Datasheet_EN.pdf, page 9, Table 10) for the detailed description.

### CODE REVIEW

**Comment by abrauchli** [comment]
Hi @dhasenfratz, Table 10 says 10ms typical, 12ms as max - 12ms would thus be the safe value.

**Comment by dhasenfratz** [comment]
Thanks @abrauchli, fixed the timing.

**Comment by abrauchli** [comment]
LGTM, :+1:

**Comment by ladyada** [comment]
thankx!

**Pull request merged**
