### PR TITLE
added methods to read raw H2 & ethanol from sensor following specifications

### PR DESCRIPTION
**Pull request by pabloandresm**
I suggest adding the sensor call "Measure_raw_signals" (0x20 0x50) to read raw H2 and ethanol values.

### CODE REVIEW

**Comment by melroy89** [comment]
Why is this not merged yet?

**Comment by ladyada** [comment]
we haven't gotten around to testing this - you could try it and let us know if it works :)

**Comment by melroy89** [comment]
I'll once I received the sensor :+1:

**Comment by hoffmannjan** [comment]
all works, tested on esp32 & uno.
due to conflicts it is moved to #07.

**Pull request closed without merging**
